### ISSUE TITLE
Option to remove saved public keys in settings?

### ISSUE THREAD

**Issue by tindtoast** [SammCheese/RepluggedPGP#3]
Hi, I was wondering if you can make a remove saved public keys button that will either remove all saved public keys or just remove a key manually selected by the user.

**Comment by SammCheese** [comment]
soon:tm:

**Comment by tindtoast** [comment]
Thanks 👍

**Comment by SammCheese** [comment]
Added in 08eeb65 (1.4.2)

**Comment by tindtoast** [comment]
nice job 👍
