### ISSUE TITLE
Edit button not working

### ISSUE THREAD

**Issue by tindtoast** [SammCheese/RepluggedPGP#4]
The edit button in the keymanager is not working, is this supposed to be intentional or a bug?

**Comment by SammCheese** [comment]
There is no edit button.

**Comment by tindtoast** [comment]
> There is no edit button.
![image](https://user-images.githubusercontent.com/92030063/232010781-a45ff1b9-5bf9-42d2-9dad-85f4af9c0562.png)

**Comment by SammCheese** [comment]
There is none. If you compiled an earlier version that included it is not my fault.

**Comment by tindtoast** [comment]
Oh, my bad

**Comment by tindtoast** [comment]
> There is none. If you compiled an earlier version that included it is not my fault.

I used the latest release in this github?

**Comment by SammCheese** [comment]
Right then it's my fault. It does nothing yet, no.
It will be changed into a "View" button anyway.

**Comment by tindtoast** [comment]
Okay thanks! Sorry if I caused any trouble btw.
