### ISSUE TITLE
[FEATURE REQUEST] Preferences for selected DM channel

### ISSUE THREAD

**Issue by Wolfhound905** [SammCheese/RepluggedPGP#5]
I think the ability to save a dm channel's preference would be cool. For example right now when I DM my friend, I have to select the pub keys every time. This could potentially lead to a misclick, and just get's repetitive. 

Could you make it so you can set the preferences for that channel once, and have the option to edit in the future?

I would just like it to where I have to put in my password, then type a message and click send.

**Comment by SammCheese** [comment]
Implemented in the latest release. You will have to copy his userid into the new "View" window in the Key Manager
